KOTLINC="../kotlinc/bin/kotlinc"
KOTLIN="../kotlinc/bin/kotlin"
JAVA="../jdk-10.0.1/bin/java"

all:
	${KOTLINC} -include-runtime -d hello-world.jar hello-world.kt

run:
	${JAVA} -jar hello-world.jar

kotlinc-help:
	${KOTLINC} -help

kotlin-help:
	${KOTLIN} -help

