KOTLINC="../kotlinc/bin/kotlinc"
KOTLIN="../kotlinc/bin/kotlin"

all:
	${KOTLINC} -include-runtime -d hello-world.jar hello-world.kt

run:
	java -jar hello-world.jar

kotlinc-help:
	${KOTLINC} -help

kotlin-help:
	${KOTLIN} -help

